name: "Test"
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - name: Install dependencies
      run: |
        npm -v
        npm install
        cd cli
        npm install
        npm install .. --no-save
        cd ..
    - name: Lint sources
      run: npm run lint:sources -- --max-warnings 0
    - name: Lint types
      run: npm run lint:types
  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node_version: ["12", "14", "lts/*"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: |
        npm -v
        npm install
        cd cli
        npm install
        npm install .. --no-save
        cd ..
    - name: Build the package
      run: npm run build
    - name: Run all tests
      run: npm test
  bench:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - name: Install dependencies
      run: |
        npm -v
        npm install
        cd cli
        npm install
        npm install .. --no-save
        cd ..
    - name: Run benchmark
      run: npm run bench
